package com.sws.rico.constant;

public enum CategoryDto {
    RUNNING, SLIPPERS, LOAFERS, SNEAKERS,
    T_SHIRT, CASUAL, SHIRT, SPORTSWEAR, BLOUSE, SWEATER,
    PANTS, JEANS, SLACKS, SWEATPANTS,
    PADDING, COAT, CARDIGAN, SUIT, OUTERWEAR,
    INNERWEAR, SOCKS, CAP, BAG
}
